import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import Link from "next/link";
import "./globals.css";
import Banner from "../components/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "1rem",
            background: "#f5f5f5",
          }}
        >
          <Banner />
          <nav
            style={{
              display: "flex",
              gap: "2rem",
              marginLeft: "auto",
            }}
          >
            <Link href="/">Home</Link>
            <Link href="/courses">Courses</Link>
            <Link href="/quizzes">Quizzes</Link>
            <Link href="/leaderboard">Leaderboard</Link>
            <Link href="/signin">Sign in</Link>
          </nav>
        </header>
        <main style={{ padding: "2rem" }}>{children}</main>
      </body>
    </html>
  );
}
